openapi: 3.0.3
info:
  title: Pet Insurance API
  version: 1.0.0
  description: API for Pet Insurance Reimbursement Platform
paths:
  /api/claims/:
    get:
      operationId: claims_list
      tags:
      - claims
      security:
      - jwtAuth: []
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Claim'
          description: ''
    post:
      operationId: claims_create
      tags:
      - claims
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                insurance:
                  type: integer
                invoice:
                  type: string
                  format: binary
                invoice_date:
                  type: string
                  format: date
                amount:
                  type: number
                  format: decimal
                date_of_event:
                  type: string
                  format: date
              required:
              - insurance
              - invoice
              - invoice_date
              - amount
              - date_of_event
      security:
      - jwtAuth: []
      - cookieAuth: []
      - basicAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Claim'
          description: ''
  /api/claims/{id}/:
    get:
      operationId: claims_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - claims
      security:
      - jwtAuth: []
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Claim'
          description: ''
    put:
      operationId: claims_update
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - claims
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ClaimRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ClaimRequest'
        required: true
      security:
      - jwtAuth: []
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Claim'
          description: ''
    patch:
      operationId: claims_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - claims
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedClaimRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedClaimRequest'
      security:
      - jwtAuth: []
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Claim'
          description: ''
    delete:
      operationId: claims_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - claims
      security:
      - jwtAuth: []
      - cookieAuth: []
      - basicAuth: []
      responses:
        '204':
          description: No response body
  /api/insurances/:
    get:
      operationId: insurances_list
      tags:
      - insurances
      security:
      - jwtAuth: []
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PetInsurance'
          description: ''
    post:
      operationId: insurances_create
      tags:
      - insurances
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PetInsuranceRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PetInsuranceRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PetInsuranceRequest'
        required: true
      security:
      - jwtAuth: []
      - cookieAuth: []
      - basicAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PetInsurance'
          description: ''
  /api/insurances/{id}/:
    get:
      operationId: insurances_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - insurances
      security:
      - jwtAuth: []
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PetInsurance'
          description: ''
    put:
      operationId: insurances_update
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - insurances
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PetInsuranceRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PetInsuranceRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PetInsuranceRequest'
        required: true
      security:
      - jwtAuth: []
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PetInsurance'
          description: ''
    patch:
      operationId: insurances_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - insurances
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedPetInsuranceRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedPetInsuranceRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedPetInsuranceRequest'
      security:
      - jwtAuth: []
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PetInsurance'
          description: ''
    delete:
      operationId: insurances_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - insurances
      security:
      - jwtAuth: []
      - cookieAuth: []
      - basicAuth: []
      responses:
        '204':
          description: No response body
  /api/pets/:
    get:
      operationId: pets_list
      tags:
      - pets
      security:
      - jwtAuth: []
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
          description: ''
    post:
      operationId: pets_create
      tags:
      - pets
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PetRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PetRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PetRequest'
        required: true
      security:
      - jwtAuth: []
      - cookieAuth: []
      - basicAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
          description: ''
  /api/pets/{id}/:
    get:
      operationId: pets_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - pets
      security:
      - jwtAuth: []
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
          description: ''
    put:
      operationId: pets_update
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - pets
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PetRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PetRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PetRequest'
        required: true
      security:
      - jwtAuth: []
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
          description: ''
    patch:
      operationId: pets_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - pets
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedPetRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedPetRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedPetRequest'
      security:
      - jwtAuth: []
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
          description: ''
    delete:
      operationId: pets_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - pets
      security:
      - jwtAuth: []
      - cookieAuth: []
      - basicAuth: []
      responses:
        '204':
          description: No response body
  /api/token/:
    post:
      operationId: token_create
      description: |-
        Takes a set of user credentials and returns an access and refresh JSON web
        token pair to prove the authentication of those credentials.
      tags:
      - token
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomTokenObtainPairRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CustomTokenObtainPairRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CustomTokenObtainPairRequest'
        required: true
      responses:
        '200':
          description: No response body
  /api/token/refresh/:
    post:
      operationId: token_refresh_create
      description: |-
        Takes a refresh type JSON web token and returns an access type JSON web
        token if the refresh token is valid.
      tags:
      - token
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRefreshRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenRefreshRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenRefreshRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenRefresh'
          description: ''
components:
  schemas:
    Claim:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        insurance:
          type: integer
        invoice:
          type: string
          format: uri
        invoice_date:
          type: string
          format: date
        amount:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
        status:
          allOf:
          - $ref: '#/components/schemas/ClaimStatusEnum'
          readOnly: true
        review_notes:
          type: string
          readOnly: true
        date_of_event:
          type: string
          format: date
        created_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - amount
      - created_at
      - date_of_event
      - id
      - insurance
      - invoice
      - invoice_date
      - review_notes
      - status
    ClaimRequest:
      type: object
      properties:
        insurance:
          type: integer
        invoice:
          type: string
          format: binary
        invoice_date:
          type: string
          format: date
        amount:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
        date_of_event:
          type: string
          format: date
      required:
      - amount
      - date_of_event
      - insurance
      - invoice
      - invoice_date
    ClaimStatusEnum:
      enum:
      - SUBMITTED
      - PROCESSING
      - IN_REVIEW
      - APPROVED
      - REJECTED
      type: string
      description: |-
        * `SUBMITTED` - Submitted
        * `PROCESSING` - Processing
        * `IN_REVIEW` - In Review
        * `APPROVED` - Approved
        * `REJECTED` - Rejected
    CustomTokenObtainPairRequest:
      type: object
      properties:
        email:
          type: string
          writeOnly: true
          minLength: 1
        password:
          type: string
          writeOnly: true
          minLength: 1
      required:
      - email
      - password
    PatchedClaimRequest:
      type: object
      properties:
        insurance:
          type: integer
        invoice:
          type: string
          format: binary
        invoice_date:
          type: string
          format: date
        amount:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
        date_of_event:
          type: string
          format: date
    PatchedPetInsuranceRequest:
      type: object
      properties:
        pet:
          type: integer
        coverage_start:
          type: string
          format: date
    PatchedPetRequest:
      type: object
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 100
        species:
          $ref: '#/components/schemas/SpeciesEnum'
        birth_date:
          type: string
          format: date
    Pet:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        owner:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 100
        species:
          $ref: '#/components/schemas/SpeciesEnum'
        birth_date:
          type: string
          format: date
      required:
      - birth_date
      - id
      - name
      - owner
      - species
    PetInsurance:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        owner:
          type: integer
          readOnly: true
        pet:
          type: integer
        coverage_start:
          type: string
          format: date
        coverage_end:
          type: string
          format: date
          readOnly: true
        status:
          allOf:
          - $ref: '#/components/schemas/PetInsuranceStatusEnum'
          readOnly: true
        created_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - coverage_end
      - coverage_start
      - created_at
      - id
      - owner
      - pet
      - status
    PetInsuranceRequest:
      type: object
      properties:
        pet:
          type: integer
        coverage_start:
          type: string
          format: date
      required:
      - coverage_start
      - pet
    PetInsuranceStatusEnum:
      enum:
      - ACTIVE
      - EXPIRED
      type: string
      description: |-
        * `ACTIVE` - Active
        * `EXPIRED` - Expired
    PetRequest:
      type: object
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 100
        species:
          $ref: '#/components/schemas/SpeciesEnum'
        birth_date:
          type: string
          format: date
      required:
      - birth_date
      - name
      - species
    SpeciesEnum:
      enum:
      - DOG
      - CAT
      - OTHER
      type: string
      description: |-
        * `DOG` - Dog
        * `CAT` - Cat
        * `OTHER` - Other
    TokenRefresh:
      type: object
      properties:
        access:
          type: string
          readOnly: true
      required:
      - access
    TokenRefreshRequest:
      type: object
      properties:
        refresh:
          type: string
          writeOnly: true
          minLength: 1
      required:
      - refresh
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
